name: Update Repository After Release

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get release info
        id: release
        run: |
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: |
          npm version ${{ steps.release.outputs.version }} --no-git-tag-version

      - name: Generate CHANGELOG
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          gh api repos/${{ github.repository }}/releases \
            --jq '.[] | "## [\(.tag_name)](\(.html_url)) (\(.published_at | split("T")[0]))\n\n\(.body)\n"' \
            >> CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update package.json and CHANGELOG for release ${{ steps.release.outputs.tag_name }}"
          title: "🤖 Update repo after release ${{ steps.release.outputs.tag_name }}"
          body: |
            Automated update after release ${{ steps.release.outputs.tag_name }}

            Changes:
            - 📦 Update package.json version to ${{ steps.release.outputs.version }}
            - 📋 Update CHANGELOG.md with latest releases

            This PR was created automatically after the release was published.
          branch: chore/update-after-release-${{ steps.release.outputs.version }}
          delete-branch: true
